services:
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.development
    env_file:
      - ./frontend/.env.development
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    ports:
      - 5173:5173
volumes:
  node_modules:
