services:
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.development
    env_file:
      - ./frontend/.env.development
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    ports:
      - 80:80
